version: "3"

services:
  postgres:
    image: "postgres:9.5"
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"

  app:
    build: .
    command: ./entrypoints/docker-entrypoint.sh
    ports:
      - "80:80"
    depends_on: 
      - postgres
    volumes:
      - .:/Blog
      - gems:/gems
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    tty: true
    stdin_open: true

  caddy:
    image: caddy/caddy:2.2.1-alpine
    container_name: caddy-service
    restart: unless-stopped
    depends_on:
      - app
    ports:
      - '443:443'
    volumes:            
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - $PWD/site:/srv
      - caddy_data:/data
      - caddy_config:/config



volumes:
  postgres:
  gems:
  caddy_data:
  caddy_config:
